--- 
- name: Take the facts of other systems.
  hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Installing vim and wget
    yum:
      name:
        - wget
        - vim
      state: latest
          